-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 17:17:03 2017
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scraper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scraper` DEFAULT CHARACTER SET utf8mb4 ;
USE `scraper` ;

-- -----------------------------------------------------
-- Table `scraper`.`urls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scraper`.`urls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `domain` VARCHAR(100) NULL,
  `url` VARCHAR(750) NULL,
  `hash` VARCHAR(32) NULL,
  `status` VARCHAR(3) NULL,
  `html` LONGTEXT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `domain_INDEX` (`domain` ASC),
  INDEX `hash_INDEX` (`hash` ASC),
  INDEX `status_INDEX` (`status` ASC),
  INDEX `created_INDEX` (`created` ASC),
  INDEX `updated_INDEX` (`updated` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scraper`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scraper`.`links` (
  `from_url_id` INT NOT NULL,
  `to_url_id` INT NOT NULL,
  INDEX `fk_links_from_url_id_idx` (`from_url_id` ASC),
  INDEX `fk_links_to_url_id_idx` (`to_url_id` ASC),
  UNIQUE INDEX `link_UNIQUE` (`from_url_id` ASC, `to_url_id` ASC),
  CONSTRAINT `fk_links_from_url_id`
    FOREIGN KEY (`from_url_id`)
    REFERENCES `scraper`.`urls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_links_to_url_id`
    FOREIGN KEY (`to_url_id`)
    REFERENCES `scraper`.`urls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
