-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 23:41:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scraper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scraper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scraper` DEFAULT CHARACTER SET utf8 ;
USE `scraper` ;

-- -----------------------------------------------------
-- Table `scraper`.`urls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scraper`.`urls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `domain` VARCHAR(45) NULL,
  `hash` VARCHAR(45) NULL,
  `html` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scraper`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scraper`.`links` (
  `from_id` INT NOT NULL,
  `to_id` INT NOT NULL,
  INDEX `fk_links_urls_from_idx` (`from_id` ASC),
  INDEX `fk_links_urls_to_idx` (`to_id` ASC),
  CONSTRAINT `fk_links_urls_from_id`
    FOREIGN KEY (`from_id`)
    REFERENCES `scraper`.`urls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_links_urls_to_id`
    FOREIGN KEY (`to_id`)
    REFERENCES `scraper`.`urls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
